import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#630037",
        "primary-container": "#880e4f",
        "on-primary": "#ffffff",
        "on-primary-container": "#ff93bc",
        "primary-fixed": "#ffd9e4",
        "primary-fixed-dim": "#ffb0cc",
        "on-primary-fixed": "#3e0020",
        "on-primary-fixed-variant": "#890f50",
        secondary: "#805062",
        "secondary-container": "#fec1d6",
        "on-secondary-container": "#7b4c5e",
        "secondary-fixed": "#ffd9e4",
        "secondary-fixed-dim": "#f2b6cb",
        "on-secondary-fixed": "#330f1f",
        "on-secondary-fixed-variant": "#65394b",
        tertiary: "#1e333c",
        "tertiary-container": "#344953",
        "on-tertiary-container": "#a1b8c3",
        "tertiary-fixed": "#cfe6f2",
        "tertiary-fixed-dim": "#b4cad6",
        "on-tertiary-fixed": "#071e27",
        "on-tertiary-fixed-variant": "#354a53",
        background: "#f8fafb",
        "on-background": "#191c1d",
        surface: "#f8fafb",
        "surface-dim": "#d8dadb",
        "surface-bright": "#f8fafb",
        "surface-variant": "#e1e3e4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f5",
        "surface-container": "#eceeef",
        "surface-container-high": "#e6e8e9",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-surface-variant": "#564148",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#eff1f2",
        "inverse-primary": "#ffb0cc",
        "surface-tint": "#a82d68",
        outline: "#897178",
        "outline-variant": "#dcbfc7",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      spacing: {
        sidebar_width: "280px",
        container_max: "1440px",
        gutter: "24px",
        margin_desktop: "40px",
        margin_mobile: "16px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
